apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-org${ORG_NUMBER}
spec:
  volumeName: fabric-org${ORG_NUMBER}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
