apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}-tls-cert
  namespace: ${NETWORK_NAME}
spec:
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - localhost
    - org${ORG_NUMBER}-orderer${ORDERER_NUMBER}
    - org${ORG_NUMBER}-orderer${ORDERER_NUMBER}.${NETWORK_NAME}.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  secretName: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}-tls-cert
  issuerRef:
    name: org${ORG_NUMBER}-tls-cert-issuer

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}-env
data:
  FABRIC_CFG_PATH: /var/hyperledger/fabric/config
  FABRIC_LOGGING_SPEC: INFO # debug:cauthdsl,policies,msp,common.configtx,common.channelconfig=info
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
  ORDERER_GENERAL_LISTENPORT: "6050"
  ORDERER_GENERAL_LOCALMSPID: OrdererMSP
  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/fabric/organizations/ordererOrganizations/org${ORG_NUMBER}.example.com/orderers/org${ORG_NUMBER}-orderer${ORDERER_NUMBER}.org${ORG_NUMBER}.example.com/msp
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/fabric/config/tls/tls.crt
  ORDERER_GENERAL_TLS_ROOTCAS: /var/hyperledger/fabric/config/tls/ca.crt
  ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/fabric/config/tls/tls.key
  ORDERER_GENERAL_BOOTSTRAPMETHOD: none
  ORDERER_FILELEDGER_LOCATION: /var/hyperledger/fabric/data/orderer${ORDERER_NUMBER}
  ORDERER_CONSENSUS_WALDIR: /var/hyperledger/fabric/data/orderer${ORDERER_NUMBER}/etcdraft/wal
  ORDERER_CONSENSUS_SNAPDIR: /var/hyperledger/fabric/data/orderer${ORDERER_NUMBER}/etcdraft/wal
  ORDERER_OPERATIONS_LISTENADDRESS: 0.0.0.0:8443
  ORDERER_ADMIN_LISTENADDRESS: 0.0.0.0:9443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}
  template:
    metadata:
      labels:
        app: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}
    spec:
      containers:
        - name: main
          image: hyperledger/fabric-orderer:${FABRIC_VERSION}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}-env
          ports:
            - containerPort: 6050
            - containerPort: 8443
            - containerPort: 9443
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config
            - name: tls-cert-volume
              mountPath: /var/hyperledger/fabric/config/tls
              readOnly: true
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: fabric-org${ORG_NUMBER}
        - name: fabric-config
          configMap:
            name: org${ORG_NUMBER}-config
        - name: tls-cert-volume
          secret:
            secretName: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}-tls-cert

---
apiVersion: v1
kind: Service
metadata:
  name: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}
spec:
  ports:
    - name: general
      port: 6050
      protocol: TCP
    - name: operations
      port: 8443
      protocol: TCP
    - name: admin
      port: 9443
      protocol: TCP
  selector:
    app: org${ORG_NUMBER}-orderer${ORDERER_NUMBER}
