apiVersion: apps/v1
kind: Deployment
metadata:
  name: org${ORG_NUMBER}-admin-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org${ORG_NUMBER}-admin-cli
  template:
    metadata:
      labels:
        app: org${ORG_NUMBER}-admin-cli
    spec:
      containers:
        - name: main
          image: ${FABRIC_CONTAINER_REGISTRY}/fabric-tools:${FABRIC_VERSION}
          imagePullPolicy: IfNotPresent
          env:
            - name: FABRIC_CFG_PATH
              value: /var/hyperledger/fabric/config
            - name: CORE_PEER_MSPCONFIGPATH
              value: /var/hyperledger/fabric/organizations/peerOrganizations/org${ORG_NUMBER}.example.com/users/Admin@org${ORG_NUMBER}.example.com/msp
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /var/hyperledger/fabric/organizations/peerOrganizations/org${ORG_NUMBER}.example.com/msp/tlscacerts/org${ORG_NUMBER}-tls-ca.pem
          args:
            - sleep
            - "2147483647"
          workingDir: /root
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config

      # This init container will unfurl all of the MSP archives listed in the msp-config config map.
      initContainers:
        - name: msp-unfurl
          image: busybox
          command:
            - sh
            - -c
            - "for msp in $(ls /msp/msp-*.tgz); do echo $msp && tar zxvf $msp -C /var/hyperledger/fabric; done"
          volumeMounts:
            - name: msp-config
              mountPath: /msp
            - name: fabric-volume
              mountPath: /var/hyperledger

      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: fabric-org${ORG_NUMBER}
        - name: fabric-config
          configMap:
            name: org${ORG_NUMBER}-config
        - name: msp-config
          configMap:
            name: msp-config
